LISTE_NAF_SELECTION = {
    "TOUS": "Tous les secteurs / Toutes activités",
    "5610A": "Restauration traditionnelle",
    "5610B": "Cafétérias et autres libres-services",
    "5610C": "Restauration de type rapide (fast-food, sandwicheries, kebabs, food trucks, etc.)",
    "5621Z": "Services des traiteurs",
    "5629A": "Restauration collective sous contrat",
    "5629B": "Autres services de restauration n.c.a.",
    "5630Z": "Débits de boissons (bars, cafés, pubs, salons de thé avec licence)",
    "1071B": "Boulangerie et boulangerie-pâtisserie",
    "1071C": "Pâtisserie fraîche",
    "1013A": "Charcuterie",
    "4120A": "Construction de maisons individuelles",
    "4321A": "Électricien (Installation électrique)",
    "4322A": "Plombier / Chauffagiste",
    "4332A": "Menuiserie bois et PVC",
    "4334Z": "Peintre / Vitrier",
    "9602A": "Coiffure (Salons et à domicile)",
    "9602B": "Soins de beauté / Esthétique",
    "4711A": "Supérettes",
    "4711B": "Épiceries sociales ou de quartier",
    "4721Z": "Fruits et légumes (Primeur)",
    "4722Z": "Boucherie / Boucherie-Charcuterie",
    "4724Z": "Pain, pâtisserie et confiserie (Revente)",
    "4725Z": "Caviste / Boissons",
    "4761Z": "Librairie",
    "4762Z": "Journaux et papeterie",
    "4771Z": "Prêt-à-porter / Habillement",
    "4773Z": "Pharmacie de détail",
    "4776Z": "Fleuriste (Fleurs, plantes, graines)",
    "4777Z": "Bijouterie / Horlogerie",
    "7410Z": "Activités spécialisées de design",
    "7111Z": "Activités d architecture",
}

TRANCHES_EFFECTIFS = {
    "TOUS": (-1, "Tous les effectifs"),
    "00": (0, "0 salarié (ou unité non employeuse)"),
    "01": (1, "1 ou 2 salariés"),
    "02": (3, "3 à 5 salariés"),
    "03": (6, "6 à 9 salariés"),
    "11": (10, "10 à 19 salariés"),
    "12": (20, "20 à 49 salariés"),
    "21": (50, "50 à 99 salariés"),
}

ORDRE_PRIORITE_QUALITES = [
    "gérant",
    "président",
    "directeur général",
    "directeur",
    "associé",
    "administrateur",
    "membre",
    "représentant",
]